# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
    - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'

    - name: Build
      run: make all
      env:
        VERSION_NUM: ${{ github.ref_name }}

    - name: PATH
      run: |
        ls -lahR;
        pwd;

    - name: release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/wggen*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
